# Kyler Adams
# Final Project
### All EDA was performed using R.  My dashboard in Power BI was generated by 
### using findings from my R code.
rm(list=ls(all=TRUE))
library(tidyverse)
library(psych)

teams <- read_csv('Teams.csv')

# I want to get the team who won the world series every year
# Since 1985
ws.winners <- teams %>%
    filter(yearID >= 1985) %>% 
    filter(WSWin == 'Y') %>% 
    select(yearID, teamID)


# Salaries by team
salaries <- read_csv('Salaries.csv')

sal.year <- salaries %>% 
    group_by(yearID, teamID) %>% 
    summarise(TeamSalary = sum(salary)) %>% 
    group_by(yearID) %>% 
    mutate(sal_by_year = mean(TeamSalary))

# Visualizing how much each team spends compared to league average, too cluttered
ggplot(sal.year, aes(yearID, TeamSalary/sal_by_year, color = teamID)) + geom_line()

# Looking at salaries of teams who won the world series
ws.winner.salary <- left_join(ws.winners, sal.year, by=c("teamID", "yearID"))

ggplot(ws.winner.salary, aes(yearID, TeamSalary/sal_by_year)) + geom_line()

# Only 7 times out of 30 has a team with below average salary won the WS
ws.winner.salary %>% 
    filter(TeamSalary <= sal_by_year)



# Combine team stats with salaries
teams_sal_stats <- left_join(teams, sal.year, by=c("teamID", "yearID")) %>% 
    filter(yearID >= 1985)

# I was going to attempt to look at how much teams pay for individual stats, but
# due to inflation and rising salaries the line graph will always be rising at a
# rapid rate.  This is something I want to revisit when I have more time.
teams_sal_stats %>% 
    group_by(yearID, teamID) %>% 
    summarise(BB.pay = TeamSalary/BB) %>% 
    group_by(yearID) %>% 
    summarise(mean = mean(BB.pay)) %>% 
    ggplot(aes(yearID, mean)) + geom_line()


#### The reason I remove years 1994 and 1995 below is that they were affected by 
#### strikes, and the seasons were shorter.  This throws off the season stats.

# What stats correlate with wins
# Runs
# Strange that hitter strikeouts has a slight positive correlation with wins.
teams %>% 
    filter(yearID >= 1970, yearID != 1994, yearID != 1995) %>% 
    select_('W', 'R', 'HR', 'BB', 'SO', 'SB', 'RA', 'SOA') %>% 
    pairs.panels()

# lots of correlations
teams %>% 
    filter(yearID >= 1970, yearID != 1994, yearID != 1995) %>% 
    select_('W', 'R', 'H', 'HR', 'BB', 'RA', 'HA', 'HRA', 'BBA') %>% 
    pairs.panels()

# correlation of run differential
# Pretty awesome that run differential has a 0.93 correlation with wins, we will
# explore this more below.
teams$rundif <- teams$R - teams$RA
teams %>% 
    filter(yearID >= 1970, !yearID %in% c(1994,1995,1973,1981)) %>% #More strike years
    select(W, R, RA, rundif) %>% 
    pairs.panels()


# what teams had the highest run differential but lost the most games
# View(
teams %>% 
    filter(yearID >= 1970, !yearID %in% c(1994,1995,1973,1981)) %>% 
    filter(rundif >= 0, W <= 80) %>% 
    select(teamID, yearID, W, L, R, RA, rundif) %>% 
    arrange(W)
# )



# some regression
teams.1970 <- teams %>% 
    filter(yearID >= 1970, !yearID %in% c(1994,1995,1973,1981))

# Every point of run differential is about .1 increase in wins.
# Stated another way, every 10 runs of positive differential is worth 1 win.
# It makes sense that the intercept is almost 81, exactly half a season, meaning
# exactly an average team.
mod.1 <- lm(W~rundif,teams.1970)
summary(mod.1)


# what creates runs
teams.1970 %>% 
    select_('R', 'AB', 'H', 'HR', 'BB', 'SO', 'SB', 'CS') %>% 
    pairs.panels()

mod.2.f <- lm(R~B2+B3+HR+BB+SO,teams.1970)
mod.2.r <- lm(R~H+BB,teams.1970)
anova(mod.2.r, mod.2.f)
summary.aov(mod.2.r)
summary(mod.2.f)
summary(mod.2.r)
# These models aren't so good, need to improve them.
# For example by definition a triple is not worth more runs than a home run.

# regression years 2008-2010
teams.2008.2010 <- teams %>% 
    filter(yearID %in% c(2008,2009,2010))


# I need to create some variables - hits per run, on base perc, slugging perc, and ISO
# on base perc: OBP = (Hits + Walks + Hit by Pitch) / (At Bats + Walks + Hit by Pitch + Sacrifice Flies)
teams.2008.2010 <- teams.2008.2010 %>% 
    mutate(OBP = as.integer(H+BB+as.numeric(HBP)) / as.integer(AB+BB+as.numeric(HBP)+as.numeric(SF)) )

# slg perc: total bases / at bats, or, single+2*double+3*triple+4*hr / ab
teams.2008.2010 <- teams.2008.2010 %>% 
    mutate(SLG = ((H-B2-B3-HR) + (2*B2) + (3*B3) + (4*HR)) / AB )

# iso: isolated slugging = slugging - average
teams.2008.2010 <- teams.2008.2010 %>% 
    mutate(ISO = SLG - (H/AB))


# hits per run
# Here I am wondering how to find on average how many runs a team should score
# based on how many hits they have.
teams.2008.2010$hpr <- teams.2008.2010$H / teams.2008.2010$R

mod.3 <- lm(hpr~OBP+ISO+SLG, teams.2008.2010)
summary(mod.3)

# is there a problem with multicolinearity?
teams.2008.2010 %>% 
    select(hpr, OBP, SLG, ISO) %>% 
    pairs.panels()

# SLG and ISO are directly related, shouldn't use them both.
# This is the better model, simpler and no multicolinearity
mod.4 <- lm(hpr~OBP+ISO, teams.2008.2010)
summary(mod.4)

# as isolated slugging increases, the amount of hits per run dramatically decreases
# This makes sense because you need 4 singles for a run, or only 1 home run for a run
teams.2008.2010 %>% 
    ggplot(aes(ISO, hpr)) + geom_point()

# Basically the same output with slugging
teams.2008.2010 %>% 
    ggplot(aes(SLG, hpr)) + geom_point()


# Which teams are getting more runs per hit
# 2010 tampa bay rays score the most runs on the fewest hits 
# most lucky or simply most powerful?  The regression says lucky.

### yfitted is the amount of hits a team should have needed to score a run based on
### their power.  A negative value means they were more lucky with hit sequencing 
### than the average team.  A positive value means they were less lucky.
teams.2008.2010 %>% 
    select(yearID, teamID, hpr, OBP, ISO) %>% 
    mutate(yfitted = (4.0922-(4.0721*OBP)-(5.1144*ISO))) %>% 
    mutate(difference = hpr - yfitted) %>% 
    arrange(difference)


# I want to measure the same as above but all years since 2001 (last time mariners made the playoffs)
teams.2002 <- teams %>% 
    filter(yearID >= 2002) #No strikes since 1994 thankfully.
teams.2002 <- teams.2002 %>% 
    mutate(OBP = as.integer(H+BB+as.numeric(HBP)) / as.integer(AB+BB+as.numeric(HBP)+as.numeric(SF)) )
teams.2002 <- teams.2002 %>% 
    mutate(SLG = ((H-B2-B3-HR) + (2*B2) + (3*B3) + (4*HR)) / AB )
teams.2002 <- teams.2002 %>% 
    mutate(ISO = SLG - (H/AB))
teams.2002$hpr <- teams.2002$H / teams.2002$R

# tampa bay rays are still on top, very interesting to see 2014 oakland as they
# had an extremely interesting 2014.  Basically were the best team in baseball 
# the first half and the worst the 2nd half.  Their 1st half was propped up by luck?
teams.2002 %>% 
    select(yearID, teamID, hpr, OBP, ISO) %>% 
    mutate(yfitted = (4.0922-(4.0721*OBP)-(5.1144*ISO))) %>% 
    mutate(difference = hpr - yfitted) %>% 
    arrange(difference)


### let's back up a bit - why haven't the mariners made the playoffs since 2001

# Testing a pythagorean model.
mod.5 <- lm(W~I(rundif^2), teams.2002)
summary(mod.5)

# Extremely important: the pythagorean theorum of base ball states:
# W% = [(Runs Scored)^1.81] / [(Runs Scored)^1.81 + (Runs Allowed)^1.81]
# I will regress on this model instead.
teams.2002$winpct <- teams.2002$W/162
teams.2002 <- teams.2002 %>% 
    mutate(pythagW = I(R^1.81) / (I(R^1.81)+I(RA^1.81)))

# Very strong R2 value.
mod.6 <- lm(winpct~pythagW, teams.2002)
summary(mod.6)

# Which teams had the most/least wins compared to their expected wins

# Using the coefficients from exact rundif
mod.1.2002 <- lm(W~rundif,teams.2002)
summary(mod.1.2002)

teams.2002 %>% 
    select(yearID, teamID, W, R, RA, rundif) %>% 
    mutate(yfitted = (80.973810+(0.101774*rundif))) %>% 
    mutate(difference = W - yfitted) %>% 
    arrange(difference)
# 2006 cleveland should have not only had 11 more wins, but should have gone from
# a losing season to a winning one, and in fact probably would have made the playoffs
# that year.


# Using pythag instead
# very close to the same
teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct) %>% 
    mutate(difference = round((winpct - pythagW),6)) %>% 
    mutate(pythagW.actual = pythagW*162) %>% 
    arrange(difference)

View(
    teams.2002 %>% 
        select(yearID, teamID, W, R, RA, pythagW, winpct) %>% 
        mutate(difference = winpct - pythagW) %>% 
        mutate(pythagW.actual = pythagW*162) %>% 
        arrange(difference) 
)
### The funny (sad?) thing is, Seattle has been mostly lucky with their winning seasons
### Not unlucky...

# What is the average amount of wins to make the playoffs?
# 0.5790638 * 162 = 93.8 wins
teams.2002 %>% 
    filter(DivWin == 'Y' | WCWin == 'Y') %>% 
    summarise(avgpct = mean(winpct))



# I want to visualize this information for the mariners
# pythag looks pretty bad for the mariners
# When you look at their expected wins, mariners should have had almost all losing
# seasons.  They are lucky to have had some winning ones in 2007,2009.
teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct) %>% 
    mutate(difference = winpct - pythagW) %>% 
    arrange(difference) %>% 
    filter(teamID == 'SEA') %>% 
    ggplot(aes(yearID, pythagW)) + geom_line() +
    scale_x_continuous(breaks=c(2002:2015))

# Mariners were very lucky in 2007,2009, unlucky in 2008, 2004/5
teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct) %>% 
    mutate(difference = winpct - pythagW) %>% 
    arrange(difference) %>% 
    filter(teamID == 'SEA') %>% 
    ggplot(aes(yearID, difference)) + geom_line() +
    scale_x_continuous(breaks=c(2002:2015))

# Tangent question - what teams had the most winning seasons when they should 
# have had losing seasons.
teams.2002 %>% 
    select(yearID, franchID, W, R, RA, pythagW, winpct) %>% 
    mutate(luckyseason = ifelse(pythagW < .5 & winpct > .5, 1, 0)) %>% 
    group_by(franchID) %>% 
    summarise(total = sum(luckyseason)) %>% 
    arrange(desc(total))

# Actual win %
teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct) %>% 
    mutate(difference = winpct - pythagW) %>% 
    arrange(difference) %>% 
    filter(teamID == 'SEA') %>% 
    ggplot(aes(yearID, winpct)) + 
    geom_line() + 
    geom_hline(yintercept = 0.5790638)
# This line doesn't work so well because this is the average wins
# What we want instead is the average *minimum* amount of wins to get in

# 0.5410053 average
minpct <- teams.2002 %>% 
    filter(DivWin == 'Y' | WCWin == 'Y') %>% 
    group_by(yearID) %>% 
    summarise(minpct = min(winpct))

# Who was the low winning team in 2003?
teams.2002 <- teams.2002 %>% 
    left_join(minpct, by = 'yearID')


######################################################
######## CODE AND GRAPHS FOR MEMO STARTS HERE ######## 
###################################################### 


teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct, minpct) %>% 
    filter(teamID == 'SEA') %>% 
    ggplot(aes(yearID, winpct)) + 
    geom_line() + 
    geom_line(aes(y = minpct), colour="blue") +
    #geom_hline(yintercept = 0.5410053) +
    scale_x_continuous(breaks=c(2002:2015)) +
    ggtitle("Since 2004, the Mariners have had only 1 year in which they had 
    a higher winning pct than the weakest team to make the playoffs.") +
         xlab("Year") + ylab("Win Percentage")


# 2007 teams
teams.2002 %>% 
    filter(yearID == 2007) %>% 
    arrange(desc(W)) %>% 
    print(n=14)



# What could have helped in 2014?
# Seattle actually tracks pythag decently.  However in 2014 we should have won more
teams.2002 %>% 
    select(yearID, teamID, W, R, RA, pythagW, winpct, minpct) %>% 
    filter(teamID == 'SEA') %>% 
    ggplot(aes(yearID, winpct)) + 
    geom_line(size=1.2) + 
    geom_line(aes(y = pythagW), colour="blue", size=1.2) +
    #geom_hline(yintercept = 0.5410053) +
    scale_x_continuous(breaks=c(2002:2015)) +
    ggtitle("Mariners win percentage in black, with Pythagorean expectation in blue") +
    xlab("Year") + ylab("Win Percentage")

# Note that below, I'm filtering on AL only because that is the specific league the Mariners play in.
# Based on pythag wins, Seattle would have made the playoffs if they played to their level
# highlighted teams made playoffs.
teams.2002 %>% 
    filter(lgID == 'AL', yearID == 2014) %>% 
    mutate(barcolor = ifelse(WCWin == 'Y' | DivWin == 'Y', 1, ifelse(teamID == 'SEA', 2, 0))) %>% 
    ggplot(aes(reorder(teamID, pythagW), pythagW, fill = as.factor(barcolor))) + 
    geom_bar(stat = "identity") +
    scale_fill_discrete(name="Legend",
                        breaks=c("0", "1", "2"),
                        labels=c("Missed Playoffs", "Reached Playoffs", "Mariners")) +
    ggtitle("All 2014 American League teams sorted by Pythagorean expectation.
    If the Mariners played to expectation in 2014, they would have made the playoffs.") +
    xlab("Year") + ylab("Pythagorean Win Percentage")


# What was every team's most wins over the past 15 years
# Actually this is pretty sad for the mariners...
teams.2002 %>% 
    filter(lgID == 'AL' | franchID == 'HOU') %>% # Houston changed leagues in 2013
    group_by(teamID) %>% 
    summarise(maxwins = max(W)) %>% 
    mutate(barcolor = ifelse(teamID == 'SEA', 1, 0)) %>% 
    ggplot(aes(reorder(teamID, maxwins), maxwins, fill = as.factor(barcolor))) + 
    geom_bar(stat = "identity") +
    theme(legend.position="none")

# Actually, the mariners 93 win seasons were in 2002-2003, the furthest years back, this may look worse...
# HOU and seattle still at the bottom.
# Seattle max of 88, HOU of 86, all other teams at least 90.
teams.2002 %>% 
    filter(lgID == 'AL', yearID >= 2004) %>% 
    group_by(franchID, yearID) %>% 
    summarise(wins = W) %>% 
    group_by(franchID) %>% 
    filter(wins == max(wins)) %>% 
    filter(yearID == max(yearID)) %>% 
    mutate(barcolor = ifelse(franchID == 'SEA', 1, 0)) %>% 
    ggplot(aes(reorder(franchID, wins), wins, fill = as.factor(barcolor))) + 
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    geom_text(aes(label = yearID), vjust = -.5) + 
    scale_y_continuous(breaks=seq(0,105,5))

# Back to 2002 for paper
teams.2002 %>% 
    filter(lgID == 'AL' | franchID == 'HOU') %>% 
    group_by(franchID, yearID) %>% 
    summarise(wins = W) %>% 
    group_by(franchID) %>% 
    filter(wins == max(wins)) %>% 
    filter(yearID == max(yearID)) %>% 
    mutate(barcolor = ifelse(franchID == 'SEA', 1, 0)) %>% 
    ggplot(aes(reorder(franchID, wins), wins, fill = as.factor(barcolor))) + 
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    geom_text(aes(label = yearID), vjust = -.5) + 
    scale_y_continuous(breaks=seq(0,105,5)) +
    ggtitle("Each American League team's highest number of wins in a season since 2002") +
    xlab("Team") + ylab("Maximum wins")

# So although seattle is very low on the max wins scale, what playoff teams made 
# the playoffs with less than 88 wins (Seattle's max)
teams.2002 %>% 
    filter(lgID == 'AL') %>% 
    mutate(playoffs = ifelse(WCWin == 'Y' | DivWin == 'Y', 1, 0)) %>% 
    filter(playoffs ==1, W < 88) %>% 
    select(yearID, franchID, W)

# Still not looking very good.  Only 3 times has a team made the playoffs with 
# less than 88 wins.  Since 2002, there would have been 59 teams in the playoffs 
# from the AL.
    


# Moving on to salaries and overpaying for statistics.
View(teams_sal_stats)

# Which teams got the most wins per dollar spent
View(
teams_sal_stats %>% 
    filter(yearID >= 2002) %>% 
    group_by(franchID, yearID) %>% 
    summarise(winsperdollar = (W / TeamSalary)) %>% 
    arrange(desc(winsperdollar))
)



# This result is per million dollars spent
View(
teams_sal_stats %>% 
    filter(yearID >= 2002) %>% 
    group_by(franchID, yearID) %>% 
    summarise(winsperdollar = (W / (TeamSalary/1000000)) ) %>% 
    arrange(desc(winsperdollar))
)



# I need to normalize this by year since salaries increase every year.
# I find it funny that all of the top 10 is the Yankees, with 1 result for LA dodgers.
# In fact, that is absolutely ridiculous that the Yankees consistently have double
# the average payroll...
teams_sal_stats %>% 
    filter(yearID >= 2002) %>% 
    group_by(franchID, yearID) %>% 
    summarise(winsperdollar = (TeamSalary / sal_by_year) ) %>% 
    arrange(desc(winsperdollar))

# factoring wins into the equation
# I put wins as the numerator so that more wins for a smaller salary will be a higher number
teams_sal_stats %>% 
    filter(yearID >= 2002) %>% 
    group_by(franchID, yearID) %>% 
    summarise(winfactor = W / (TeamSalary / sal_by_year) ) %>% 
    arrange(desc(winfactor))
# Here I'm getting some teams which were really really bad, but spent no money.
# I need to filter this to teams which are at least respectable.
# Filter on teams which played at least .500 ball.
teams_sal_stats %>% 
    filter(yearID >= 2002, W >= 81) %>% 
    group_by(franchID, yearID) %>% 
    summarise(winfactor = W / (TeamSalary / sal_by_year) ) %>% 
    arrange(desc(winfactor))
# Interesting that the marlins are still on top.


# I'm more interested in player statistics than simply wins per dollar
mod.7 <- lm(TeamSalary~R+RA, teams_sal_stats)
summary(mod.7)
# Strong relationship between salary and runs scored and runs allowed, 
# However it appears that teams are spending more for offense than defense.


# Below is some mutation in order to get the league average price per win compared
# to the mariners price per win
teams_sal_stats <- teams_sal_stats %>% 
    group_by(yearID) %>% 
    mutate(avgdollarperwin = sal_by_year/mean(W))

sea_sal_stats <- teams_sal_stats %>% 
    group_by(yearID, teamID) %>% 
    filter(teamID == 'SEA') %>% 
    mutate(SEAdollarperwin = TeamSalary/W) %>% 
    select(yearID, SEAdollarperwin)


# Joining the table of mariners wins per dollar with team averages
teams_sal_stats <- left_join(teams_sal_stats, sea_sal_stats, by=c("yearID"))


# Fixing this table after the join
teams_sal_stats <- teams_sal_stats %>% 
    select(-teamID.y, teamID = teamID.x) %>% 
    filter(yearID >= 2002)

# Looking at the amount the Mariners spend per win compared to the rest of the leage
ggplot(teams_sal_stats, aes(yearID)) + 
    geom_line(aes(y = avgdollarperwin, colour = "avgdollarperwin")) +
    geom_line(aes(y = na.omit(SEAdollarperwin), colour = "SEAdollarperwin"))




# What is the value of each type of hit?
teams.2002 <- teams.2002 %>% 
    mutate(singles = (H-B2-B3-HR))

# Value of each type of hit.
mod.8 <- lm(R~0+singles+B2+B3+HR, teams.2002)
summary(mod.8)

# I'm curious about revisiting my model from earlier.
mod.9 <- lm(R~OBP+ISO, teams.2002)
summary(mod.9)

# Knowing these values, what runs do we expect?
teams.2002 <- teams.2002 %>% 
    mutate(exp_runs_by_hits = (0.24857*singles) + (0.79314*B2) + (0.89400*B3) + (1.44733*HR) )

teams.2002 <- teams.2002 %>% 
    mutate(exp_runs_by_hits_diff = R - exp_runs_by_hits )

# Wow this is interesting, the 2015 mariners should have scored 81 more runs.
# If they had scored 81 more runs, their pythag would have been at least a winning record
teams.2002 %>% 
    arrange(desc(exp_runs_by_hits_diff)) %>% 
    select(yearID, teamID, R, exp_runs_by_hits, exp_runs_by_hits_diff)
# Notice that the 2010 TB rays appear at (near) the top again.


teams.2002 %>% 
    arrange(exp_runs_by_hits_diff) %>% 
    select(yearID, teamID, R, exp_runs_by_hits, exp_runs_by_hits_diff) %>% 
    filter(teamID == "SEA") %>% 
    ggplot(aes(yearID, exp_runs_by_hits_diff)) + 
    geom_bar(stat = "identity", position = "dodge", fill = "blue") +
    scale_x_continuous(breaks=c(2002:2015)) +
    ggtitle("Since 2008, the Mariners have consistently scored less runs than expected") +
    xlab("Year") + ylab("Actual runs minus expected runs")





# I will export my data frames so that I can use them in powerBI
write_csv(teams.2002, "export/teams.2002.csv")
write_csv(teams_sal_stats, "export/teams_sal_stats.csv")
